interface Heap {
    void Heap();
    void insert(long element, double value);
    long extract();
    long size();
};

interface Deque {
    void Deque();
    void push(long long element);
    void shift(long long element);
    long long pop();
    long long unshift();
    long size();
};